const data = {
    products: [
        {
            name: 'Free Shirt',
            category: 'Shirts',
            slug: 'free-shirt',
            image: '/images/shirt1.webp',
            price: 70,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },{
            name: 'bamboo Shirt',
            category: 'Shirts',
            slug: 'bamboo-shirt',
            image: '/images/shirts2.jpg',
            price: 90,
            brand:'softs',
            rating: 4.0,
            numReviews: 50,
            countInStock: 60,
            description: 'A quality tee',
        },{
            name: 'slick cargos',
            category: 'trousers',
            slug: 'slick-cargos',
            image: '/images/trousers1.jpg',
            price: 120,
            brand:'bts',
            rating: 5.0,
            numReviews: 15,
            countInStock: 40,
            description: 'really comfortable pants',
        },{
            name: 'kiddys',
            category: 'trousers',
            slug: 'kiddys',
            image: '/images/trousers2.jpg',
            price: 95,
            brand:'river island',
            rating: 4.5,
            numReviews: 20,
            countInStock: 55,
            description: 'A classic',
        },{
            name: 'louis stacks',
            category: 'shackets',
            slug: 'louis-stacks',
            image: '/images/shackets1.jpg',
            price: 150,
            brand:'louis',
            rating: 4.0,
            numReviews: 45,
            countInStock: 70,
            description: 'A popular overshirt',
        },{
            name: 'Free shacket',
            category: 'shackets',
            slug: 'free-shackets',
            image: '/images/shackets2.jpg',
            price: 30,
            brand:'H&M',
            rating: 4.5,
            numReviews: 160,
            countInStock: 80,
            description: 'A cool overshirt',
        },{
            name: 'litty coat',
            category: 'coats',
            slug: 'litty-coat',
            image: '/images/coats1.jpg',
            price: 70,
            brand:'lizzy',
            rating: 4.5,
            numReviews: 19,
            countInStock: 30,
            description: 'A stylish overcoat',
        },{
            name: 'slim coat',
            category: 'coats',
            slug: 'slim-coat',
            image: '/images/coats2.jpg',
            price: 75,
            brand:'Nike',
            rating: 4.5,
            numReviews: 17,
            countInStock: 90,
            description: 'A thick coat',
        },
    ]
}
export default data;
